### ISSUE TITLE
Linting/Parsing Errors with Tailwind v4 new rules

### ISSUE THREAD

**Issue by xcrap** [biomejs/biome-zed#63]
In the left, Zed, in the right, VSCode

Why I have no linting/parser errors in VSCode but I do in Zed ?
Any idea how can I handle this?

<img width="3008" alt="Screenshot 2024-11-29 at 11 19 36" src="https://github.com/user-attachments/assets/88d569a5-1738-43fc-8e26-39a5eb494939">

**Comment by ematipico** [comment]
In VSCode, you can see on the bottom right that Biome doesn't recognise it while Biome is present. 

This often happens if you map a file language to another one. The Tailwind VSCode extension maps `css` files to `tailwindcss` (or something similar), when Biome LSP receives the file, it sees `tailwindcss` as language, and it doesn't know how to parse it.

**Comment by ematipico** [comment]
Here there's an issue: https://github.com/biomejs/biome-vscode/issues/388

**Comment by ematipico** [comment]
Also, another FYI, tailwind uses unsupported CSS syntax, that's why Biome can't parse them. As for now, you're better off ignoring those files.

**Comment by xcrap** [comment]
Yeah I was really trying to avoid another biome.json config to ignore the css files... ergh... I could not find a way to disable in Zed Settings for CSS files or maybe I was doing it wrong, thanks for all the info :)
